name: CTest Actions Bug Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  RunCTest:
    name: Windows CTest Actions Bug Demo
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        env:
          QT_DIR: ${{ github.workspace }}\5.15.2\msvc2019_64
        run: |
          pip install aqtinstall
          python -m aqt install 5.15.2 windows desktop win64_msvc2019_64
          Add-Content -Path $env:GITHUB_ENV -Value "CMAKE_PREFIX_PATH=$env:QT_DIR;$env:QT_DIR\lib\cmake"
          Add-Content -Path $env:GITHUB_PATH -Value "${{ env.qt_dir }}"
          Add-Content -Path $env:GITHUB_PATH -Value "${{ env.qt_dir }}\bin"

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest --output-on-failure --output-log log.txt | Out-Null
          type log.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: CTest Logs
          path: log.txt
